### ISSUE TITLE
Follow JavaScript conventions

### ISSUE THREAD

**Issue by jetersen** [jenkinsci/jcasc-vscode-extension#9]
### Your checklist for this issue

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Link to any upstream changes that might be required (for example Jenkins Core pull request)

### Feature Request

Follow javascript conventions.

Please see 
https://google.github.io/styleguide/jsguide.html#formatting-block-indentation
https://github.com/airbnb/javascript#whitespace
https://www.w3schools.com/js/js_conventions.asp

Not sure why json and ts files are using tabs when all Javascript convention says 2 space indents.

You can use [prettier](https://prettier.io/) for auto formatting (comes as a vscode extension even)

**Comment by sladyn98** [comment]
@casz I expected  prettier extension to do the work for me, am I missing something :/

**Comment by jetersen** [comment]
You have to configure prettier and install the npm package.

**Comment by jetersen** [comment]
fixed in #24
